version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    directory: "/various"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker-test"
    schedule:
      interval: "daily"
